/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjSistemaHoteis_Telas;

import java.sql.Connection;
import java.sql.Time;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import prjSistemaHoteis_Connection.Modulo_ConexaoMySQL;

/**
 *
 * @author rapha
 */
public class Tela_Principal extends javax.swing.JFrame {

    Connection conexao = null;

    public void DataHora_Atual() {
        Thread th;
        th = new Thread(() -> {
            while (true) {
                Date Data = Calendar.getInstance().getTime();
                DateFormat d = DateFormat.getDateInstance();
                DateFormat h = DateFormat.getTimeInstance();
                lblData.setText(d.format(Data));
                lblHorario.setText(h.format(Data));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {

                }
            }
        });
        th.start();
    }

    public void Logout() {
        this.dispose();
        Tela_Login Login = new Tela_Login();
        Login.setVisible(true);
    }

    public Tela_Principal() {

        initComponents();
        conexao = Modulo_ConexaoMySQL.Conexao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelInformacoes = new javax.swing.JPanel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        MenuPainel = new javax.swing.JDesktopPane();
        lblLogin = new javax.swing.JLabel();
        MenuSistema = new javax.swing.JMenuBar();
        MenReservas = new javax.swing.JMenu();
        MenGerenciarReservas = new javax.swing.JMenuItem();
        MenReservasHospedes = new javax.swing.JMenuItem();
        MenQuartos = new javax.swing.JMenu();
        MenQuartosGerHospedagens = new javax.swing.JMenuItem();
        MenAdmin = new javax.swing.JMenu();
        MenAdminUsuarios = new javax.swing.JMenuItem();
        MenAdminQuartos = new javax.swing.JMenuItem();
        MenAdminProdServ = new javax.swing.JMenuItem();
        MenRelatorios = new javax.swing.JMenu();
        menRelReservas = new javax.swing.JMenuItem();
        menRelFuncionarios = new javax.swing.JMenuItem();
        menRelHospedes = new javax.swing.JMenuItem();
        menRelServicos = new javax.swing.JMenuItem();
        menRelQuartos = new javax.swing.JMenuItem();
        menRelDependentes = new javax.swing.JMenuItem();
        MenLogout = new javax.swing.JMenu();
        MenLogoutConfirm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Hotel Nome - Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PainelInformacoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        lblTipoUsuario.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        lblTipoUsuario.setText("TipoUsuario");

        lblNome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblNome.setText("Nome");

        lblHorario.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        lblHorario.setText("Horário");

        lblData.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        lblData.setText("Data");

        javax.swing.GroupLayout PainelInformacoesLayout = new javax.swing.GroupLayout(PainelInformacoes);
        PainelInformacoes.setLayout(PainelInformacoesLayout);
        PainelInformacoesLayout.setHorizontalGroup(
            PainelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PainelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHorario)
                    .addComponent(lblData)
                    .addComponent(lblTipoUsuario)
                    .addComponent(lblNome))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        PainelInformacoesLayout.setVerticalGroup(
            PainelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInformacoesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblNome)
                .addGap(15, 15, 15)
                .addComponent(lblTipoUsuario)
                .addGap(15, 15, 15)
                .addComponent(lblData)
                .addGap(15, 15, 15)
                .addComponent(lblHorario)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        MenuPainel.setPreferredSize(new java.awt.Dimension(800, 600));

        lblLogin.setText("LOGIN");

        MenuPainel.setLayer(lblLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MenuPainelLayout = new javax.swing.GroupLayout(MenuPainel);
        MenuPainel.setLayout(MenuPainelLayout);
        MenuPainelLayout.setHorizontalGroup(
            MenuPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPainelLayout.createSequentialGroup()
                .addContainerGap(759, Short.MAX_VALUE)
                .addComponent(lblLogin)
                .addContainerGap())
        );
        MenuPainelLayout.setVerticalGroup(
            MenuPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogin)
                .addContainerGap())
        );

        MenReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/online-booking.png"))); // NOI18N

        MenGerenciarReservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenGerenciarReservas.setText("Gerenciar reservas");
        MenGerenciarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenGerenciarReservasActionPerformed(evt);
            }
        });
        MenReservas.add(MenGerenciarReservas);

        MenReservasHospedes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenReservasHospedes.setText("Gerenciar hóspedes");
        MenReservasHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenReservasHospedesActionPerformed(evt);
            }
        });
        MenReservas.add(MenReservasHospedes);

        MenuSistema.add(MenReservas);

        MenQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/bed.png"))); // NOI18N
        MenQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenQuartosActionPerformed(evt);
            }
        });

        MenQuartosGerHospedagens.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenQuartosGerHospedagens.setText("Gerenciar hospedagens");
        MenQuartosGerHospedagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenQuartosGerHospedagensActionPerformed(evt);
            }
        });
        MenQuartos.add(MenQuartosGerHospedagens);

        MenuSistema.add(MenQuartos);

        MenAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/admin-with-cogwheels.png"))); // NOI18N
        MenAdmin.setEnabled(false);

        MenAdminUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MenAdminUsuarios.setText("Funcionários");
        MenAdminUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAdminUsuariosActionPerformed(evt);
            }
        });
        MenAdmin.add(MenAdminUsuarios);

        MenAdminQuartos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MenAdminQuartos.setText("Quartos");
        MenAdminQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAdminQuartosActionPerformed(evt);
            }
        });
        MenAdmin.add(MenAdminQuartos);

        MenAdminProdServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        MenAdminProdServ.setText("Produtos e serviços");
        MenAdminProdServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAdminProdServActionPerformed(evt);
            }
        });
        MenAdmin.add(MenAdminProdServ);

        MenuSistema.add(MenAdmin);

        MenRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/printer.png"))); // NOI18N
        MenRelatorios.setEnabled(false);

        menRelReservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        menRelReservas.setText("Reservas");
        menRelReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelReservasActionPerformed(evt);
            }
        });
        MenRelatorios.add(menRelReservas);

        menRelFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menRelFuncionarios.setText("Funcionários");
        menRelFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelFuncionariosActionPerformed(evt);
            }
        });
        MenRelatorios.add(menRelFuncionarios);

        menRelHospedes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        menRelHospedes.setText("Hóspedes");
        menRelHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelHospedesActionPerformed(evt);
            }
        });
        MenRelatorios.add(menRelHospedes);

        menRelServicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menRelServicos.setText("Serviços");
        menRelServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelServicosActionPerformed(evt);
            }
        });
        MenRelatorios.add(menRelServicos);

        menRelQuartos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        menRelQuartos.setText("Quartos");
        menRelQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelQuartosActionPerformed(evt);
            }
        });
        MenRelatorios.add(menRelQuartos);

        menRelDependentes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        menRelDependentes.setText("Dependentes");
        menRelDependentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelDependentesActionPerformed(evt);
            }
        });
        MenRelatorios.add(menRelDependentes);

        MenuSistema.add(MenRelatorios);

        MenLogout.setBorder(null);
        MenLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/exit.png"))); // NOI18N
        MenLogout.setToolTipText("Logout");
        MenLogout.setContentAreaFilled(false);
        MenLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenLogout.setPreferredSize(new java.awt.Dimension(64, 64));

        MenLogoutConfirm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        MenLogoutConfirm.setText("Logout");
        MenLogoutConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenLogoutConfirmActionPerformed(evt);
            }
        });
        MenLogout.add(MenLogoutConfirm);

        MenuSistema.add(MenLogout);

        setJMenuBar(MenuSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MenuPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(PainelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1066, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenAdminQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAdminQuartosActionPerformed
        Tela_MenuQuartos MenuQuartos = new Tela_MenuQuartos();
        MenuQuartos.setVisible(true);

        MenuPainel.add(MenuQuartos);
    }//GEN-LAST:event_MenAdminQuartosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DataHora_Atual();
    }//GEN-LAST:event_formWindowOpened

    private void MenGerenciarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenGerenciarReservasActionPerformed
        Tela_MenuReservas MenuReservas = new Tela_MenuReservas();
        MenuPainel.add(MenuReservas);
        String login = "";
        try {
            MenuReservas.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        MenuReservas.setVisible(true);

    }//GEN-LAST:event_MenGerenciarReservasActionPerformed

    private void MenQuartosGerHospedagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenQuartosGerHospedagensActionPerformed
        Tela_GerenciarHospedagens AdminProdutos = new Tela_GerenciarHospedagens();
        MenuPainel.add(AdminProdutos);
        try {
            AdminProdutos.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        AdminProdutos.setVisible(true);

    }//GEN-LAST:event_MenQuartosGerHospedagensActionPerformed

    private void MenAdminUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAdminUsuariosActionPerformed
        Tela_AdminUsuarios AdminUsuarios = new Tela_AdminUsuarios();
        MenuPainel.add(AdminUsuarios);
        try {
            AdminUsuarios.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        AdminUsuarios.setVisible(true);
    }//GEN-LAST:event_MenAdminUsuariosActionPerformed

    private void MenReservasHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenReservasHospedesActionPerformed
        Tela_MenuHospedes MenuHospedes = new Tela_MenuHospedes();
        MenuPainel.add(MenuHospedes);
        try {
            MenuHospedes.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        MenuHospedes.setVisible(true);
    }//GEN-LAST:event_MenReservasHospedesActionPerformed

    private void MenQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenQuartosActionPerformed
        Tela_MenuQuartos MenuQuartos = new Tela_MenuQuartos();
        MenuQuartos.add(MenuPainel);
        try {
            MenuQuartos.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        MenuQuartos.setVisible(true);
    }//GEN-LAST:event_MenQuartosActionPerformed

    private void MenLogoutConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenLogoutConfirmActionPerformed
        Logout();
    }//GEN-LAST:event_MenLogoutConfirmActionPerformed

    private void MenAdminProdServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAdminProdServActionPerformed
        Tela_AdmProdutosServicos AdminProdServ = new Tela_AdmProdutosServicos();

        MenuPainel.add(AdminProdServ);
        try {
            AdminProdServ.setMaximum(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        AdminProdServ.setVisible(true);


    }//GEN-LAST:event_MenAdminProdServActionPerformed

    private void menRelReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelReservasActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão do relátorio ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint Print = JasperFillManager.fillReport("C:\\Reports\\Reservas.jasper", null, conexao);
                JasperViewer.viewReport(Print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelReservasActionPerformed

    private void menRelHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelHospedesActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão do relátorio ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint Print = JasperFillManager.fillReport("C:\\Reports\\Hospedes.jasper", null, conexao);
                JasperViewer.viewReport(Print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelHospedesActionPerformed

    private void menRelServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelServicosActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão do relátorio ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint Print = JasperFillManager.fillReport("C:\\Reports\\ProdutosServicos.jasper", null, conexao);
                JasperViewer.viewReport(Print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelServicosActionPerformed

    private void menRelQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelQuartosActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão do relátorio ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint Print = JasperFillManager.fillReport("C:\\Reports\\Quartos.jasper", null, conexao);
                JasperViewer.viewReport(Print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelQuartosActionPerformed

    private void menRelDependentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelDependentesActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão do relátorio ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint Print = JasperFillManager.fillReport("C:\\Reports\\Dependentes.jasper", null, conexao);
                JasperViewer.viewReport(Print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelDependentesActionPerformed

    private void menRelFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelFuncionariosActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão do relátorio ?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint Print = JasperFillManager.fillReport("C:\\Reports\\Funcionarios.jasper", null, conexao);
                JasperViewer.viewReport(Print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menRelFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenAdmin;
    private javax.swing.JMenuItem MenAdminProdServ;
    private javax.swing.JMenuItem MenAdminQuartos;
    public javax.swing.JMenuItem MenAdminUsuarios;
    private javax.swing.JMenuItem MenGerenciarReservas;
    private javax.swing.JMenu MenLogout;
    private javax.swing.JMenuItem MenLogoutConfirm;
    private javax.swing.JMenu MenQuartos;
    private javax.swing.JMenuItem MenQuartosGerHospedagens;
    public javax.swing.JMenu MenRelatorios;
    private javax.swing.JMenu MenReservas;
    private javax.swing.JMenuItem MenReservasHospedes;
    private javax.swing.JDesktopPane MenuPainel;
    private javax.swing.JMenuBar MenuSistema;
    private javax.swing.JPanel PainelInformacoes;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHorario;
    public javax.swing.JLabel lblLogin;
    public javax.swing.JLabel lblNome;
    public javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenuItem menRelDependentes;
    private javax.swing.JMenuItem menRelFuncionarios;
    private javax.swing.JMenuItem menRelHospedes;
    private javax.swing.JMenuItem menRelQuartos;
    private javax.swing.JMenuItem menRelReservas;
    private javax.swing.JMenuItem menRelServicos;
    // End of variables declaration//GEN-END:variables
}
