package prjSistemaHoteis_Telas;

import java.sql.*;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import prjSistemaHoteis_Connection.Modulo_ConexaoMySQL;

public class Tela_MenuQuartos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void RemoverQuarto() {
     String sql = "delete from quarto where CodQuarto=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodQuarto.getText());

            if ((txtCodQuarto.getText().isEmpty()) || (cmbStatusQuarto.getSelectedItem().toString().isEmpty()) || (cmbTipoQuarto.getSelectedItem().toString().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            } else {
                int removido = pst.executeUpdate();
                if (removido > 0) {
                    JOptionPane.showMessageDialog(null, "Quarto removido do sistema com sucesso.");
                    txtCodQuarto.setText(null);
                    cmbStatusQuarto.setSelectedIndex(0);
                    cmbTipoQuarto.setSelectedIndex(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void EditarQuarto() {
        String sql = "update quarto set StatusQuarto=?, TipoQuarto=? where CodQuarto=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, cmbStatusQuarto.getSelectedItem().toString());
            pst.setString(2, cmbTipoQuarto.getSelectedItem().toString());
            pst.setString(3, txtCodQuarto.getText());
            if ((txtCodQuarto.getText().isEmpty()) || (cmbStatusQuarto.getSelectedItem().toString().isEmpty()) || (cmbTipoQuarto.getSelectedItem().toString().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            } else {
                int atualizado = pst.executeUpdate();
                if (atualizado > 0) {
                    JOptionPane.showMessageDialog(null, "Quarto alterado no sistema com sucesso.");
                    txtCodQuarto.setText(null);
                    cmbStatusQuarto.setSelectedIndex(0);
                    cmbTipoQuarto.setSelectedIndex(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void AdicionarQuarto() {
        String sql = "insert into quarto(CodQuarto, StatusQuarto, TipoQuarto) values (?, ?, ?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodQuarto.getText());
            pst.setString(2, cmbStatusQuarto.getSelectedItem().toString());
            pst.setString(3, cmbTipoQuarto.getSelectedItem().toString());

            if ((txtCodQuarto.getText().isEmpty()) || (cmbStatusQuarto.getSelectedItem().toString().isEmpty()) || (cmbTipoQuarto.getSelectedItem().toString().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Quarto adicionado no sistema com sucesso.");
                    txtCodQuarto.setText(null);
                    cmbStatusQuarto.setSelectedIndex(0);
                    cmbTipoQuarto.setSelectedIndex(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void SetarCampos() {
        int setar = tabelaQuartos.getSelectedRow();
        txtCodQuarto.setText(tabelaQuartos.getModel().getValueAt(setar, 0).toString());
        cmbStatusQuarto.setSelectedItem(tabelaQuartos.getModel().getValueAt(setar, 1).toString());
        cmbTipoQuarto.setSelectedItem(tabelaQuartos.getModel().getValueAt(setar, 2).toString());
    }

    public void PesquisarQuartos() {
        String sql = "select CodQuarto as Número, StatusQuarto as Status, TipoQuarto as Tipo from quarto where CodQuarto like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPesquisarQuarto.getText() + "%");
            rs = pst.executeQuery();
            tabelaQuartos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public Tela_MenuQuartos() {
        initComponents();
        conexao = Modulo_ConexaoMySQL.Conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisarQuarto = new javax.swing.JTextField();
        lblPesquisarQuarto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaQuartos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodQuarto = new javax.swing.JTextField();
        cmbStatusQuarto = new javax.swing.JComboBox<>();
        btnAddQuarto = new javax.swing.JButton();
        btnEditarQuarto = new javax.swing.JButton();
        btnRemQuarto = new javax.swing.JButton();
        cmbTipoQuarto = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Menu Quartos - Administração");
        setPreferredSize(new java.awt.Dimension(570, 568));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        lblPesquisarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/pesquisar.png"))); // NOI18N

        tabelaQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaQuartosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaQuartos);

        jLabel1.setText("Nº Quarto:");

        jLabel2.setText("Status:");

        jLabel4.setText("Tipo:");

        cmbStatusQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível", "Indisponível", " " }));

        btnAddQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/plus.png"))); // NOI18N
        btnAddQuarto.setToolTipText("Adicionar quarto");
        btnAddQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddQuarto.setPreferredSize(new java.awt.Dimension(64, 64));
        btnAddQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQuartoActionPerformed(evt);
            }
        });

        btnEditarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/exchange.png"))); // NOI18N
        btnEditarQuarto.setToolTipText("Editar quarto");
        btnEditarQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarQuarto.setPreferredSize(new java.awt.Dimension(64, 64));
        btnEditarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarQuartoActionPerformed(evt);
            }
        });

        btnRemQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/x-button.png"))); // NOI18N
        btnRemQuarto.setToolTipText("Remover quarto");
        btnRemQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemQuarto.setPreferredSize(new java.awt.Dimension(64, 64));
        btnRemQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemQuartoActionPerformed(evt);
            }
        });

        cmbTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Duplo", "Família", "Luxo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279)
                        .addComponent(btnRemQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtPesquisarQuarto)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblPesquisarQuarto))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCodQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(cmbStatusQuarto, javax.swing.GroupLayout.Alignment.LEADING, 0, 110, Short.MAX_VALUE)
                                    .addComponent(cmbTipoQuarto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatusQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTipoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemQuarto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        PesquisarQuartos();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tabelaQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaQuartosMouseClicked
        SetarCampos();
        btnAddQuarto.setEnabled(false);
        txtCodQuarto.setEnabled(false);
    }//GEN-LAST:event_tabelaQuartosMouseClicked

    private void btnAddQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQuartoActionPerformed
        AdicionarQuarto();
        PesquisarQuartos();
    }//GEN-LAST:event_btnAddQuartoActionPerformed

    private void btnEditarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarQuartoActionPerformed
        EditarQuarto();
        PesquisarQuartos();
        btnAddQuarto.setEnabled(true);
        txtCodQuarto.setEnabled(true);
    }//GEN-LAST:event_btnEditarQuartoActionPerformed

    private void btnRemQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemQuartoActionPerformed
        RemoverQuarto();
        PesquisarQuartos();
        btnAddQuarto.setEnabled(true);
        txtCodQuarto.setEnabled(true);
    }//GEN-LAST:event_btnRemQuartoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddQuarto;
    private javax.swing.JButton btnEditarQuarto;
    private javax.swing.JButton btnRemQuarto;
    private javax.swing.JComboBox<String> cmbStatusQuarto;
    private javax.swing.JComboBox<String> cmbTipoQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisarQuarto;
    private javax.swing.JTable tabelaQuartos;
    private javax.swing.JTextField txtCodQuarto;
    private javax.swing.JTextField txtPesquisarQuarto;
    // End of variables declaration//GEN-END:variables
}
