package prjSistemaHoteis_Telas;

import java.sql.*;
import javax.swing.JOptionPane;
import prjSistemaHoteis_Connection.Modulo_ConexaoMySQL;

public class Tela_Login extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void Logar() {
        String sql = "select * from funcionario where LoginUsuario=? and SenhaUsuario=?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtLogin.getText());
            pst.setString(2, txtPassword.getText());

            rs = pst.executeQuery();
            if (rs.next()) { //Se existir algum usuário correspondente.
                String TipoUsuario = rs.getString(6); //Coluna referente ao tipo do usuário.
                if (TipoUsuario.equals("Administrador")) { //Tratamento de usuário admin
                    Tela_Principal MenuPrincipal = new Tela_Principal();
                    MenuPrincipal.setVisible(true);
                    MenuPrincipal.lblNome.setText(rs.getString(2));
                    MenuPrincipal.lblTipoUsuario.setText(rs.getString(6));
                    MenuPrincipal.lblLogin.setText(txtLogin.getText());
                    MenuPrincipal.MenAdmin.setEnabled(true);
                    MenuPrincipal.MenRelatorios.setEnabled(true);
                    this.dispose(); //Adicionar if else gerente e recepção
                } else if (TipoUsuario.equals("Gerente")) {
                    Tela_Principal MenuPrincipal = new Tela_Principal();
                    MenuPrincipal.setVisible(true);
                    MenuPrincipal.lblNome.setText(rs.getString(2));
                    MenuPrincipal.lblTipoUsuario.setText(rs.getString(6));
                    MenuPrincipal.MenAdmin.setEnabled(true);
                    MenuPrincipal.MenRelatorios.setEnabled(true);
                    this.dispose();
                } else {
                    Tela_Principal MenuPrincipal = new Tela_Principal();
                    MenuPrincipal.setVisible(true);
                    MenuPrincipal.lblNome.setText(rs.getString(2));
                    MenuPrincipal.lblTipoUsuario.setText(rs.getString(6));
                    this.dispose();
                }
                conexao.close(); //Finalizar a conexão.
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválido(s).");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public Tela_Login() {
        initComponents();
        getRootPane().setDefaultButton(btnEntrar);
        conexao = Modulo_ConexaoMySQL.Conexao();
        if (conexao != null) {
            lblConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/dbok.png")));
        } else {
            lblConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/dberror.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblConnection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Hotel Nome - Login");
        setResizable(false);

        lblLogin.setText("Login:");

        lblPassword.setText("Senha:");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        txtLogin.setText("admin");

        txtPassword.setText("admin");

        lblConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjSistemaHoteis_Icones/dberror.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConnection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(btnEntrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLogin)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEntrar)
                    .addComponent(lblConnection))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 269));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Logar();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblConnection;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
